### ISSUE TITLE
Support laser scanners

### ISSUE THREAD

**Issue by AlexZCP** [capacitor-community/barcode-scanner#100]
Hi guys!

Can you tell if this plugin support some hardware like laser scanners (etc. in Zebra or Sunme devices).
If not, point me to maybe already existing capacitor plugin?

Thanks much.

**Comment by thegnuu** [comment]
I don't think that supporting laser scanners should be part of this plugin since it is a different use case and every vendor uses their own SDKs.

I know about some old cordova plugins providing this function, but they are all based on a specific vendor (which makes sense) and I don't know how well they are maintained. If you can tell me which devices you want to use I might be able to help you find something...

But I guess the easiest, or maybe not the easiest but the best way would be to use the vendor SDK and create a custom plugin for your use case, this should not be a to complex task since you don't have to implement a lot of functionality.

You can find more details about creating an Android plugin here: https://capacitorjs.com/docs/plugins/android

**Comment by thegnuu** [comment]
I am closing this issue for now based on the previous comment
