### ISSUE TITLE
We may need to be aware of rMQR

### ISSUE THREAD

**Issue by tomfong** [capacitor-community/barcode-scanner#126]
rMQR (Rectangular Micro QR Code) is a new form of QR code invented by Denso Wave.

https://webstore.iec.ch/publication/76135

**Comment by thegnuu** [comment]
Since we are depending on other libraries to do the encoding, there is not much we can do to support those codes. Once the other libs support codes like this it should not be a problem to update to a recent version and add support, but usually it takes a long time anyway to introduce some new formats.... :)
