### ISSUE TITLE
Add css class to HTML element

### ISSUE THREAD

**Issue by heinerlamprecht** [capacitor-community/barcode-scanner#141]
Would it be possible to add a certain css class to the HTML element instead (or in addition) to the style attribute?  This would easily allow to style certain UI elements in the application when scanning is active.

**Comment by thegnuu** [comment]
Technically this would not be a problem, but I think this is something that should be handled individually by each developer since it is really easy to implement and some might want different classes or add those classes to different elements aso...

**Comment by thegnuu** [comment]
I will close this and rewrite the docs to help with this issue :)

**Comment by CD-UNCC** [comment]
@thegnuu did this ever happen? in response to your reply, an id or single class would be a huge help just for targeting, then developers could style this thing much easier and add remove classes easier. We cant just target the last div in the body to accurately get the camera as other things may be getting attached to the body. 

I was suprised when using this library that instead of the common problem is getting the camera to show up I was greeted with a massive black box that overtook the entire application with no easy way to style

![image](https://github.com/capacitor-community/barcode-scanner/assets/5580440/99281be6-4dc5-4680-bdd9-2481ec71d25a)

(this is an app with lots of UI above and ionic tab navigation below the camera)
