### ISSUE TITLE
Add support for multiple scan (multiple barcode at once)

### ISSUE THREAD

**Issue by HunSpeedi** [capacitor-community/barcode-scanner#168]
I saw that there was a [question](https://github.com/capacitor-community/barcode-scanner/issues/43#issuecomment-852062612) regarding continuous scanning. And got me wondering if it is possible to scan multiple barcodes at once.
So not just continuously scanning without closing the camera but capturing all the visible barcodes in the image in one go.

**Comment by thegnuu** [comment]
With the current implementation this is not working really well. The currently used libs on Android and iOS will only return the first detected code (if you center to another code, this should be de the first detected and therefore it is kind of possible), the "multiple option" is disable since the results are not consistent at all.

We are working on a MLKit rewrite which should make this possible and should provide better results, but I guess the initial version will keep the "one code at a time" behaviour. But it should be possible to read up to 10 codes in a more consistent way than the actual implementation. The new version will then provide a stream of all the detected codes and the logic which one to use aso. has to be handled by de developer :)

**Comment by smachi** [comment]
@thegnuu Any advances on the ml-kit implementation?

**Comment by thegnuu** [comment]
@smachi Let me check that, someone else is working on the Android part at the moment :)

@HunSpeedi there is currently a branch, but only the iOS version is working. There are still small things to do, but in general it should work.

**Comment by thegnuu** [comment]
@HunSpeedi I just received a PR for the Android implementation. I will do my best to check and merge this ASAP so you have a version to play around with. I hope I can finish it by the end of this week :)

**Comment by thegnuu** [comment]
@HunSpeedi @smachi I just release `v5.0.0-beta.1`, the initial pre-release which uses `ml-kit`! There is still some work to be done, but I should deliver quite good results already :)

**Comment by HunSpeedi** [comment]
@thegnuu Thank you!! I hope I will have some time in the near future to try it!!
