### ISSUE TITLE
why i cannot get scan result?

### ISSUE THREAD

**Issue by Jellybing** [capacitor-community/barcode-scanner#173]
when i use like this:
<img width="440" alt="image" src="https://user-images.githubusercontent.com/16889803/202658003-2ea5b426-980d-4089-b66f-5e5e0469fafa.png">

but,i cannot get the result ,how can i get this,thanks.

**Comment by Jellybing** [comment]
and i can see it consoled this result
<img width="983" alt="image" src="https://user-images.githubusercontent.com/16889803/202658789-a9babaef-f2e3-4470-b2ac-ed89a8dee31a.png">

**Comment by NLueg** [comment]
But isn't the URL `https://vrimar.github.io/...` the content of the QR-Code you scanned?

**Comment by thegnuu** [comment]
@Jellybing I am not really sure what exactly your issue is ;)

For me it looks like you are missing your `console.log` because you are filtering for info messages in your log, if you want your message to appear there you need to use `console.info`, but your result should be visible if you show all messages...

**Comment by thegnuu** [comment]
I will close this for now, feel free to reopen if you still have issues...
