### ISSUE TITLE
getting error on build

### ISSUE THREAD

**Issue by cqsDeepakVerma27** [capacitor-community/barcode-scanner#175]
\android\src\main\java\com\getcapacitor\community\barcodescanner\BarcodeScanner.java:3: error: package android.content does not exist
import static android.content.Context.MODE_PRIVATE;
                             ^

**Comment by thegnuu** [comment]
This is usually not an issue of the plugin itself, this might happen if your `@capacitor/...` module versions are not matching and the issue is created by capacitor itself, for example using an older cli version than the android package or something like that.

Try updating all your dependencies to matching versions and maybe you need to delete your `android` folder and add it again with `npx cap add android` (make sure to setup permissions properly after this is done). This should cleanup things and you should  be able to use the plugin.

There is nothing more I can do unfortunately ;)
