### ISSUE TITLE
Not All QR are Readable

### ISSUE THREAD

**Issue by ayami123** [capacitor-community/barcode-scanner#179]
[this image](https://www.google.com/url?sa=i&url=https%3A%2F%2Fphilsysonline.com%2Fphilippine-national-id-parts%2F&psig=AOvVaw0mPurmFuTOO7nFSh6LfBnC&ust=1670818680847000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCPCP5-Ha8PsCFQAAAAAdAAAAABAE)

scanning this QR doesn't work with the barcode scanner

**Comment by thegnuu** [comment]
This is indeed possible. The quality of the code is quite bad, some tests with different tools show a ~55% recognition rate, which might not be enough depending on the version (android/zxing or ios/avfoundation) and the device (camera resolution aso.)  you are using.

This is one of the test results:
```
Succeed to identify : 40747
Failed to identify : 34707
Recognition rate : 54%
```
This is of course not a bullet proof rating since it really depends on the libraries used to read the code.

There is not much I can do on the current main branch of the plugin I assume. But I did a quick test on the upcoming update I am working on and I was able to scan the code with my IPhone 14 Pro Max and my Pixel 6 without any issues.

You can find the WIP version of this update in the `ml-kit` branch, unfortunately is not completely finished and I am not sure how long it will take me to finish things up before I can release a beta version of it. Maybe I can strip some features I am working on to speed up the process and add them in a future release.

**Comment by huuhait** [comment]
i dont think this qrcode can scan by other tool

**Comment by ayami123** [comment]
@huuhait  it can be scanned by Samsung QR weird though

**Comment by thegnuu** [comment]
As I said there are not a lot of options of improvement with the current implementation, you need to wait until we were able to switch to the `ml-kit` implementation.

We won't spend time on enhancing the current version as of now, as long as there are no critical bugs that needs to be fixed.

**Comment by thegnuu** [comment]
`v5.0.0-beta.1` should provide better results :)
