### ISSUE TITLE
Not implemented on web error

### ISSUE THREAD

**Issue by Jonathan-Dobson** [capacitor-community/barcode-scanner#188]
**Describe the bug**
Not implemented on web error at BarcodeScannerWeb.checkPermission (web.ts:51:1)

**To Reproduce**
Setup a starter barcode scanner according to instructions in readme

**Screenshots**
<img width="427" alt="image" src="https://user-images.githubusercontent.com/52715503/213692479-edb78a0c-fa6a-45e5-a544-c9d59be38369.png">

**Version**
[e.g. v1.0.0]

**Desktop (please complete the following information):**

- OS: mac 12
- Browser chrome
- 108

**Comment by thegnuu** [comment]
@Jonathan-Dobson this is right, this plugin does not support `web` as environment, only `ios` and `android` are supported.
The original plan was to add support, but since we are currently rewriting the plugin to ml-kit (which only runs natively) we will not add web support in the upcoming future.

It should be possible for you to implement web support by yourself, there are a lot of libraries out there to achieve your goal.

Sorry I cannot provide you better news on this one :)
