### ISSUE TITLE
Scan Product and Get Info Product

### ISSUE THREAD

**Issue by gassssty** [capacitor-community/barcode-scanner#215]
Hi guys! First of all, this plugin is AWESOME because is perfect for Ionic 6... you know, must of the plugins that are in the market are incompatible with this version.

Well, what I want is that...: I want to scan the barcode and, if you know any API or plugin for Ionic, or something that does that, I would appreciate it. I saw this page: 'https://www.barcodelookup.com/api' but is not free (it costs a lot).
I want, if it possible, a free usage plugin / api / whatever... and if you know, of course haha.

Well, this is all! Thank you very much to the team and greetings! :D

**Comment by thegnuu** [comment]
Hi @gassssty

I think you need to find another place to find your question, you won't find a proper answer here since nobody able to answer your question will find it here ;)

In general, you will need some sort of API, since this is a ton of data and someone needs to keep all that stuff up2date I am pretty sure you won't find any free version of an API like this.

Since this issue is not related to the plugin itself and it is the wrong place for your question I will close it.

**Comment by gassssty** [comment]
Okay sorry...

**Comment by gassssty** [comment]
Okay. Don't worry, I appreciate it but finally I will not use this, only I'll use the code, it was my mistake D;

Thank you very much by the way!
