### ISSUE TITLE
Scanner QR no Working

### ISSUE THREAD

**Issue by xhnl21** [capacitor-community/barcode-scanner#260]
**Describe the bug**
project where the scanner does not work
https://github.com/xhnl21/Scanner-QR/tree/main/ScannerQR-V1

**To Reproduce**

when clicking the button the scanner does not turn on the camera

**Version**
[ v1.0.0]
[Android]

**Comment by thegnuu** [comment]
The camera is starting as expected, please check the documentation.
You need to make sure, that your DOM background is transparent, which is not the case in your example.

**Comment by xhnl21** [comment]
good afternoon, I made sure that the DOM of the app has a transparent background.
I have no positive results, if you could help me I would appreciate it

**Comment by thegnuu** [comment]
I am not really sure how to achieve this in vue since I never used it before, the only thing I did to verify that it works was starting your repo and set every DOM element to transparent manually with the inspect tool. This way everthing worked on my end, it should not be that hard to find out which elements/classes/variables cause the issue if you do the same thing ☺️
