### ISSUE TITLE
Web/PWA support

### ISSUE THREAD

**Issue by digaus** [capacitor-community/barcode-scanner#31]
Would be nice if this plugin can have a web implementation so we can use it in PWA apps :)

**Comment by tripodsgames** [comment]
At this moment im using this library for PWA: https://github.com/zxing-js/library

**Comment by thegnuu** [comment]
Currently our first priority is to fix other issues regarding iOS and Android since a PWA solution is easier to work around than the native stuff. It is of course not ideal, but at least most devs should be able to get a working solution since adding this feature does not require any knowledge of the native environment and most capacitor devs should be able to get things working.

Once the other issues are fixed I will look into this, if someone is willing to add some functionality in the meantime that would be awesome! Just open a PR ;) Unfortunately I can't say when I will have time to look into this.

**Comment by achacofe** [comment]
@thegnuu @hellokingdom @tripodsgames  Could you point me to a scanner plugin for BarCodes, QR, etc. that has support for Web, Android and iOS?

**Comment by thegnuu** [comment]
I have not tested it, but there is one listed in the ionic docs which seems to support all platforms right now:

https://ionicframework.com/docs/native/barcode-scanner

**Comment by achacofe** [comment]
Hello, I have tried that plugin, but it does not work in the browser as I expect, what it does on the web is open a dialog for me to enter the barcode, what I want is for it to open the cam to scan. 
I am using the same example from the link. You can help me?

**Comment by tafelnl** [comment]
@achacofe This is not the right place to ask questions about other libraries. You could start out with a Google search (like https://www.google.com/search?q=barcode+scanner+npm) or open a question on Stack Overflow for example.

**Comment by tripodsgames** [comment]
> @thegnuu @hellokingdom @tripodsgames Could you point me to a scanner plugin for BarCodes, QR, etc. that has support for Web, Android and iOS?

You can use qr-scanner on the web and this library on native app

qr-scanner:
https://www.npmjs.com/package/qr-scanner

**Comment by luckydonald** [comment]
As the android version is already using `zxing`, how about the typescript port of that, `zxing-js`?
https://github.com/zxing-js/library

**Comment by iBobik** [comment]
This plugin works on the web.

**Comment by thegnuu** [comment]
I will close this for now. The current stable release supports PWAs partially and I will rewrite the pre-release to another plugin which should provide better results than the current `zxing-js` implementation in the upcoming weeks.
