### ISSUE TITLE
Error: "BarcodeScanner" plugin is not implemented on android

### ISSUE THREAD

**Issue by call-me-adas** [capacitor-community/barcode-scanner#60]
**Describe the bug**
After i follow configurations steps and running it both on device and emulator i get error ```Error: "BarcodeScanner" plugin is not implemented on android```

**Version**
2.01

**Comment by tafelnl** [comment]
Please try debugging a little more. If you really cannot get it to work, please share a repo to reproduce the issue. Otherwise I cannot help you.

**Comment by gabriel-arrvda** [comment]
i had the same error when i was updating my capacitor to v3 and i deleted the whole code inside the class MainActivity on `MainActivity.java`

**Comment by tafelnl** [comment]
This comment might help you: https://github.com/capacitor-community/barcode-scanner/issues/57#issuecomment-884080027

**Comment by gabriel-arrvda** [comment]
well i forgot to say that after i deleted that part of code it works, sorry my fault

**Comment by oldjazjef** [comment]
I know the issue is already closed, but I would like to add some notes.
I got the same error "plugin is not implemented on android".
The reason in my case for this was the used angular "monorepo" project structure. 

Capacitor checks package.json for plugins. 
Because my ionic project within the monorepo under projects/my-app had a package.json, capacitor used this to check for plugins to include under android/capacitor.settings.gradle.
Dependencies in monorepos are installed in the root of the repo, the capacitor plugins (e.g BarcodeScanner) were listed in the root package.json instead of the apps package.json.

So if you run into a similiar problem, list the npm package for the capacitor plugin within your apps package.json "dependencies".
