### ISSUE TITLE
Use IntentIntegrator for better 1D Performance

### ISSUE THREAD

**Issue by ADMIADev** [capacitor-community/barcode-scanner#69]
While Testing this plugin for our application i found out that the performance for 1D Barcode. (Code-39) is not as good as in our old nativ application. Both use the zxing libarary. The difference is in our old app we use IntentIntegrator to show the Scanner. 
I implemented IntentIntegrator into this plugin if you are interrested. Also the torch would be easier with IntentIntegrator and the backgorund of the Application would not have to be hidden becuse a custom Activity is started.

**Comment by tafelnl** [comment]
Using the `IntentIntegrator` prevents us from being able to overlay the ScanView with the WebView. This, in turn, prevents us from being able to style the Barcode Scanner using the WebView. This is a major feature of this plugin. So I am not going to replace it with the `IntentIntegrator`. But we could consider it as an extra feature, although that adds major complexity. So that makes it a long term nice-to-have feature in my opinion.

**Comment by tafelnl** [comment]
But feel free to open a PR that adds this functionality.

**Comment by ADMIADev** [comment]
Okay makes sense i will create a pull request with the IntentIntegrator functionality.
