### ISSUE TITLE
Make use of Capacitor's `Camera.requestPermissions()`

### ISSUE THREAD

**Issue by GeorgiyZhuravlev** [capacitor-community/barcode-scanner#70]
First of all - Cool plugin, thank you!

I was playing a bit with permissions and found that if access to camera once granted by the official Capacitor Camera plugin, then no need to ask again - yours works just fine.
Even more, this line in manifest becomes optional then:
```
<uses-permission android:name="android.permission.CAMERA" />
```
I played more, and found that it would be even more convenient to use "consent popup" shown by `Camera.requestPermissions()`, then to ask people to go to App settings -> permissions.

I'm not an Android developer and, maybe, I'm missing something. Could you confirm that it is a good flow, if your app is using Capacitor's Camera plugin anyway (for other purposes)

If so, it probably deserves to be mentioned in the docs.

**Comment by tafelnl** [comment]
Do you mean that this plugin only allows for requesting the permission by redirecting the user to the app settings? Because that is not the case.

As stated in the [docs](https://github.com/capacitor-community/barcode-scanner#permissions), you can request permissions through the [`checkPermission`](https://github.com/capacitor-community/barcode-scanner/blob/main/API_REFERENCE.md#checkpermission) method.

This line: `<uses-permission android:name="android.permission.CAMERA" />` is NEVER optional. It could be that you've already set it because you are using another plugin which requires you to set that line also. But it is never optional. You should always make sure to set it.

Also you _could_ use the `Camera.requestPermissions()` method to request permissions. But it is not guaranteed to work in combination with this plugin in the future. So you should use it at your own risk. Therefore I will not mention this in the docs.

Please correct me if I am misunderstanding your question.
